# herpailib/infrastructure/repository/interfaces.py
from typing import TypeVar, Protocol, Optional
from ..db.base_entity import BaseEntity

T = TypeVar('T', bound=BaseEntity)

class IRepository(Protocol[T]):
    async def create(self, **kwargs) -> T: ...
    async def get(self, id: str) -> Optional[T]: ...
    async def update(self, id: str, **kwargs) -> Optional[T]: ...
    async def delete(self, id: str) -> bool: ...